---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  deploy_stage:
    executor: aws-cli/default
    environment:
      ECS_CLUSTER: test
      ECS_SERVICE: wordpress
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_stage

      - run:
          name: Deploy task with new version
          command: |
            export AWS_DEFAULT_REGION=$AWS_STAGE_DEFAULT_REGION
            aws ecs list-tasks --cluster $ECS_CLUSTER --service $ECS_SERVICE | awk '{system("aws ecs stop-task --cluster $ECS_CLUSTER --reason \"CircleCI deployment\" --task "$2)}'

  deploy_prod:
    environment:
      ECS_CLUSTER: prod
      ECS_SERVICE: wordpress
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_prod

      - run:
          name: Deploy task with new version
          command: |
            aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only: development
      - deploy_prod_approval:
          type: approval
          filters:
            branches:
              only: main
      - deploy_prod:
          filters:
            branches:
              only: main

