---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  deploy_stage:
    executor: aws-cli/default
    environment:
      ECS_CLUSTER: test
      ECS_SERVICE: wordpress
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_stage
      - run:
          name: wp-content
          command: cp -rf ./wp-content /var/www/html/

  deploy_prod:
    environment:
      ECS_CLUSTER: prod
      ECS_SERVICE: wordpress
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_prod
      - run:
          name: wp-content
          command: cp -rf ./wp-content /var/www/html/
          
workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only: development
      - deploy_prod:
          filters:
            branches:
              only: main

